version: "3.9"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
      - cache
    command: ["sh", "-c", "npx prisma migrate deploy && node src/app.js"]
    volumes:
      - .:/app
    working_dir: /app

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  cache:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata:
